# Generated by Django 5.0.3 on 2024-04-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_status_predicted_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='screensharing',
            field=models.BooleanField(default=False),
        ),
    ]
