# Generated by Django 5.0.3 on 2024-05-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_roommember_screensharing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
    ]
